# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build lp-native`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t lp-native`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system lp-native && \
          adduser --system -G lp-native lp-native

COPY dist/lp-native lp-native/
RUN chown -R lp-native:lp-native .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix lp-native --omit=dev -f install

CMD [ "node", "lp-native" ]
